### ISSUE TITLE
Copy .env script broken

### ISSUE THREAD

**Issue by parsepixel** [theplanworks/wordpress-starter-kit#8]
The current path to the `copy-env.sh` in the composer.json scripts that runs during `post-install-cmd` will work as expected by prefacing with `./`

As it is currently, you have to manually copy the .env-sample by hand

```
"scripts": {
     ...
     "post-install-cmd": [
         "./code/scripts/copy-env.sh"
     ],
     ...
}
```

**Comment by mixaster** [comment]
updated
